puppetlabs/puppetlabs-mysql

lib/puppet/type/mysql_grant.rb, lib/puppet/type/mysql_user.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/acceptance/types/mysql_user_spec.rb, spec/unit/puppet/type/mysql_user_spec.rb
Don't fail on validation where the user isn't quoted with special
characters. The providers quote these strings by default.
=> MODULES-1520 - update username validation

lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_user.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb, tests/mysql_user.pp
Besides the default mysql_native_password there are more plugins available:
* mysql_old_password (pre 4.1 passwords, support for it will be dropped in MySQL 5.7)
* sha256_password (since 5.6?, more secure and stored a salted sha256 hash in authentication_string (instead of storing a non salted SHA1 hash in the password field)
* unix socket authentication
* PAM authentication
* Windows authentication
* No login (similar to /usr/sbin/nologin)
This PR makes it possible to define users which are authenticated by an authentication plugin.
Possible improvements:
* Support CREATE USER xxx IDENTIFIED WITH yyy USING zzz
* It seems like MariaDB 10.x+ uses IDENTIFIED VIA instead if IDENTIFIED WITH
* There is no good way to change the authentication plugin (See https://bugs.mysql.com/bug.php?id=67449 …
=> Support for authentication plugins

README.md
Setting a password for root@localhost, but leaving other accounts like root@127.0.0.1 unprotected leaves an false impression of security. This makes the example more secure.
=> Make sure the example is somewhat secure

manifests/server/account_security.pp, spec/classes/mysql_server_account_security_spec.rb
Make sure not to declare root@localhost and @localhost if the fqdn is 'localhost'
```
Error: Duplicate declaration: Mysql_user[root@localhost] is already declared in file /etc/puppet/modules/mysql/manifests/server/root_password.pp:11; cannot redeclare at /etc/puppet/modules/mysql/manifests/server/account_security.pp:11 on node localhost
Error: Duplicate declaration: Mysql_user[root@localhost] is already declared in file /etc/puppet/modules/mysql/manifests/server/root_password.pp:11; cannot redeclare at /etc/puppet/modules/mysql/manifests/server/account_security.pp:11 on node localhost
```
Also remove root@localhost.localdomain and @localhost.localdomain in that case
=> Do the right thing when fqdn==localhost

lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_user.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb, tests/mysql_user.pp
Reverts puppetlabs/puppetlabs-mysql#640
Authentication plugins are not supported on older versions of MySQL [1], which are installed by default on most supported operating systems. We would like to come up with a better way of supporting this feature without breaking the providers for older version of MySQL. In the mean time, we're reverting this pull request while we work out an alternate implementation.
[1] http://dev.mysql.com/doc/refman/5.5/en/pluggable-authentication.html
=> Revert "Support for authentication plugins"

tests/init.pp
Remove tests/init.pp which seeks to test class mysql.
There is no definition for it, and so there is no need for the init.pp file in tests.
=> there is no class called mysql anymore (to test)

lib/puppet/parser/functions/mysql_password.rb, lib/puppet/type/mysql_user.rb, spec/unit/puppet/functions/mysql_password_spec.rb
https://tickets.puppetlabs.com/browse/MODULES-1676
This is identical to what PASSWORD('') in MySQL does:
```
5.6.22-debug-log> CREATE USER 'testpwd'@'localhost' IDENTIFIED BY 'foo';
Query OK, 0 rows affected (0.03 sec)
5.6.22-debug-log> SELECT User,Host,Password FROM mysql.user WHERE
User='testpwd';
+---------+-----------+-------------------------------------------+
| User    | Host      | Password                                  |
+---------+-----------+-------------------------------------------+
| testpwd | localhost | *F3A2A51A9B0F2BE2468926B4132313728C250DBF |
+---------+-----------+-------------------------------------------+
1 row in set (0.01 sec)
5.6.22-debug-log> SET PASSWORD FOR 'testpwd'@'localhost' = PASSWORD('');
Query OK, 0 rows affected (0.00 sec)
5.6.22-debug-log> SELECT …
```
=> Return an empty string for an empty input.

lib/puppet/type/mysql_grant.rb
grants that happen before a user is created cause an ERROR 1396
=> Make grant autorequire user

README.md, lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_user.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb, tests/mysql_user.pp
This uses CREATE USER xxx IDENTIFIED WITH yyy
For tests:
unix_socket is not loaded by default, so this might require:
install plugin unix_socket soname 'auth_socket.so';
The mysql_native_password plugin is available by default and
allows you to also set a password.
Try to make it compatible with MySQL < 5.5.7 it uses version
specific code with "/*!50508 stmt */"
Previous pull request: puppetlabs/puppetlabs-mysql#640 and rollback: puppetlabs/puppetlabs-mysql/pull/644
=> Support authentication plugins

metadata.json
Mysql 3.1.0 included 08a66b7 which uses dirname() which was released in
stdlib 4.1.0. This change bumps the minimum stdlib up to 4.1.0
=> Bugfix: increase minimum stdlib

lib/puppet/parser/functions/mysql_dirname.rb, manifests/server/config.pp, metadata.json
Backported dirname => mysql_dirname since updating dependency to stdlib
4.1.0 is backwards incompatible with some versions of PE.
=> MODULES-1759: Remove dependency on stdlib >=4.1.0

README.md, manifests/params.pp, manifests/server.pp, manifests/server/root_password.pp, spec/classes/mysql_server_spec.rb
This allows the galera module and others to write ${::root_home}/.my.cnf
independently from create the mysql user. This is useful for cluster
setups where you want to create ${::root_home}/.my.cnf on every node
but create the user only once.
=> Add new parameters create_root_user and create_root_my_cnf.

examples/server/config.pp
```
examples/server/config.pp - ERROR: trailing whitespace found on line 2
```
=> Fix rake lint error in examples/server/config.php

manifests/server/root_password.pp, spec/classes/mysql_server_spec.rb
the recently added feature to support galera by allowing independent
creation of the root@localhost user in the DB and the /root/.my.cnf
file contains a bug.
specifically the .my.cnf file resource still requires the root@localhost
resource, even when it is not available.
this fixes the issue by making the dependency optional.
=> Fix bug in 578

README.md, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp, templates/meb.cnf.erb
Add backup providers for
* mysqldump
* MySQL Enterprise Backup
* Percona XtraBackup
=> Use backup providers

manifests/server/config.pp
As reported by @larkit-ian in PR #596
=> Check for full path for log-bin to stop puppet from managing directory “."

manifests/server/config.pp
puppetlabs-mysql has a dependency on stdlib 3.2.0, which does not
include the dirname function.
=> PR 654 was incorrectly using stdlib dirname

manifests/server/service.pp, spec/classes/mysql_server_spec.rb
The mysqld log-error setting may be passed by override_options, but
server/service.pp was not using the overridden value. This fixes that.
=> (MODULES-1804) Allow override of log-error

README.md, manifests/client.pp, manifests/client/install.pp, manifests/params.pp, manifests/server.pp, manifests/server/install.pp, spec/classes/mysql_client_spec.rb, spec/classes/mysql_server_spec.rb
This patch adds a package_manage parameter for both mysql::server and mysql::client
=> (MODULES-1143) Add package_manage parameters

manifests/server/service.pp
With latest (3.2.0), if you try use manage_config_file => false, you get an undefined resource for File['mysql-config-file'].
This is because mysql::server::config is conditionally defining that resource, but mysql::server::service is always requiring it.
A different approach to fixing this issue, which arguably has a bit more flexibility for the module end user, would be to leave the code in mysql::server::service as-is, and instead change mysql::server::config so that it always defines a File resource for mysql-config-file, but if manage_config_file is false, it doesn't set any attributes for the File.  That allows people to use manage_config_file => false and potentially manage their config some other way, but still have the right ordering for the file and the service resources.
=> Only set up ordering between the config file and the service if we're managing the config file.

manifests/params.pp, manifests/server/service.pp
This is a first step in OpenBSD support, tested with mysql-server-5.1.73p0v0 package on OpenBSD 5.6-current, using the following configuration stored in hiera.
```yaml
mysql::server::root_password: topsecret
mysql::server::manage_config_file: true
mysql::server::purge_conf_dir: true
mysql::server::package_ensure: present
mysql::server::service_enabled: true
mysql::server::remove_default_accounts: true
mysql::server::users:
'dashboard@localhost':
ensure: present
max_connections_per_hour: 0
max_queries_per_hour: 0
max_updates_per_hour: 0
max_user_connections: 0
password_hash: '*TOPSECRETTOPSECRETTOPSECRET'
mysql::server::grants:
'dashboard@localhost/dashboard_production.*':
ensure: present
options:
- GRANT
privileges:
- ALL
table: 'dashboard_production.*'
user: dashboard@localhost …
```
=> Add OpenBSD support.

manifests/server/service.pp
In the case of an unmanaged mysql service, defined with:
```puppet
class {'::mysql::server':
[...]
service_manage => false,
[...]
}
```
We have the following error:
```
Undefined variable "service_ensure"
```
In this case, we don't want to have it "started" nor "stopped", as it is managed by another application (in our case by pacemaker).
This patch resolve this issue, by setting `service_ensure` to `undef`, in the case of an unmanaged service.
=> Manage service only if managed

README.md, manifests/params.pp, manifests/server.pp, manifests/server/service.pp
The pull request referring to was #567 
Add a $mysql_group parameter, and use that instead of the $root_group
parameter to define the group membership of the mysql error log file.
For all OS but OpenBSD, the value is set to 'mysql', which was hardcoded
in manifests/server/service.pp before, for OpenBSD, it's set to '_mysql'.
Should bring back old behavior on non-OpenBSD, and some tests showed, 
no problems on OpenBSD.
=> Fix regression introduced by adding OpenBSD support.

templates/my.cnf.pass.erb
Add a comment in the .my.cnf file, to show that the file is managed by puppet, as in the other templates.
=> Cosmetic: add comment managed by puppet

manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp
due to a mishappen rebase, in #649, we introduced a regression fixed
which was fixed in #655.
how come our tests don't catch this?
=> mysql backup: fix regression in mysql_user call

manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, templates/mysqlbackup.sh.erb
The `mysql::backup::*` classes still use the hardcoded group name `root`, which is not available on FreeBSD systems. This patch changes this to use the param `mysql::params::root_group` instead. Besides that it utilizes `/bin/sh` instead of `/bin/bash` on systems other than Linux.
=> fix FreeBSD support for backups

manifests/server/service.pp, spec/acceptance/mysql_server_spec.rb
Wrap the file resource so that this doesn't explode if log-error is
undef. This is required for syslogging.
=> MODULES-1928 - allow log-error to be undef

manifests/backup/xtrabackup.pp
I did a simple modification in order to correctly retrieve the value of $backupdir into the crontab definition.
=> Bugfix on Xtrabackup crons

manifests/server.pp, manifests/server/install.pp, manifests/server/installdb.pp
The current install pattern used by this module is the following:
1. Install package
2. Install the DB
3. Make the config files
In some cases this prevents MySQL to start, because some variables in
the config file have an impact on the DB installation.
Example with a custom innodb_data_file_path:
[ERROR] InnoDB: space header page consists of zero bytes in data file
/var/lib/mysql/ibdata
This commit changes the order to do:
1. Install package
2. Make the config files
3. Install the DB
=> Split package installation and database install

lib/puppet/provider/mysql_grant/mysql.rb
We have 2 problems with current privileges change behaviour with puppetlabs-mysql:
1. If user doesn't have GRANT privilege, puppet will fail
2. if we want to add ALTER privilege (for example) to ['SELECT', 'INSERT'], we don't want to REVOKE SELECT, INSERT before.
=> MODULES-1981: Revoke and grant difference of old and new privileges

README.md, manifests/params.pp, manifests/server.pp
As far as I could tell this parameter is not used anywhere.
=> Remove references to old_root_password (cleanup)

manifests/server/service.pp
Currently the package dependency relies on the service name when it
should be relying on the package name.
=> (MODULES-2077) Fixes wrong dependency variable

spec/spec_helper_acceptance.rb
puppetlabs-release is not required anymore. run_puppet_install_helper
takes care of all that.
=> spec_helper_acceptance: Remove conflicting yum install

manifests/server/service.pp
With parser = future this fails with
```Error: Evaluation Error: Operator '[]' is not applicable to a Nil Object.```
We need to first check if $mysql::server::override_options is set to prevent this problem.
=> fix Evaluation Error with future parser

lib/puppet/type/mysql_grant.rb, lib/puppet/type/mysql_user.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb, spec/unit/puppet/type/mysql_user_spec.rb
Starting MariaDB 10.0.0, usernames are now 80 long.
Our mysql_user and mysql_grant types now take that into consideration.
=> length check for usernames should take mysql version into consideration

lib/facter/mysql_server_id.rb
Sometimes the macaddress fact fails, for example sometimes in a Docker
container. We shouldn't clutter up reports with spurious warnings in
that case.
=> Don't explode if macaddress isn't set

README.md, manifests/params.pp, metadata.json
This adds support for Solaris 11.2, 11.3 and 12.0 to the puppetlabs-mysql module.
=> Add Solaris support to MySQL module

.gitignore, manifests/server/root_password.pp
For puppet versions that support it, suppress diffing root's password.
=> (maint) don't print diff root password in diff

metadata.json
SLES 10 has mysql 5.0.26 in its repo, and 5.0.40 is the oldest that this
module even has a hope to work on, so it has never worked.
=> Remove sles 10 from metadata.json

README.md, lib/puppet/type/mysql_database.rb, lib/puppet/type/mysql_user.rb, manifests/db.pp
this is a rebase and fix up of https://github.com/puppetlabs/puppetlabs-mysql/pull/586
this pr closes MODULES-1685.
=> [#puppethack] do not require mysql::server when using mysql::db

.gitignore, manifests/server/root_password.pp
=> Dont print root

manifests/server/config.pp, spec/classes/mycnf_template_spec.rb
Running RHEL 7.1, puppetlabs-mysql is not idempotent.
After a second run, puppet tries to change the SElinux context:
/File[mysql-config-file]/seltype: seltype changed 'etc_t' to
'mysqld_etc_t'
Since packaging already manages SElinux labels, we should not let
Puppet doing it (default behavior).
This patch aims to set selinux_ignore_defaults to True for the
mysql-config-file File resource.
Thanks to that patch, Puppet will be indempotent between all runs on
RHEL platforms.
=> Ensure idempotency between Puppet runs

manifests/server/root_password.pp
show_diff is set twice on .my.cnf causing compilation error:
Parameter 'show_diff' is already set on File[/.my.cnf]
This patch removes one of them
=> Fix show_diff already set on .my.cnf

manifests/params.pp, manifests/server.pp, manifests/server/root_password.pp, spec/classes/mysql_server_spec.rb
I haven't written any tests for this PR b/c I wasn't sure you'd be willing to merge it. If you're OK with this approach, I will write tests. If you're not, please provide some feedback on an alternate way to address this "feature".
New installations of MySQL will configure a default random password for the root user with an expiration. See http://datacharmer.blogspot.com/2012/11/mysql-568-broken-compatibility-ahead.html. Until the root password is changed, no actions can be performed. This PR adds detection of the mysql_secret file and removes this password. If the user desires to set a password it will be configured by the mysql_user resource further down in the mysql::server::root_password class.
=> Remove default install root password if set

CHANGELOG.md, README.md, metadata.json
Diff https://github.com/puppetlabs/puppetlabs-mysql/compare/3.5.0...3.6.x
=> Prep 3.6.0

manifests/server/installdb.pp, spec/classes/mysql_server_spec.rb
This code have been remove here https://github.com/puppetlabs/puppetlabs-mysql/commit/4bab65edcb98f82f87a4414840fe90ab81b6cea3#diff-0938042fe2382aeb10032aa7f8444995 but it is required otherwise we get an `Evaluation Error: Unknown variable: 'install_db_args'.` when using `manage_config_file = false`
=> Fix when not managing config file

lib/facter/mysql_server_id.rb, spec/unit/facter/mysql_server_id_spec.rb
Fixes unique server_id within my.cnf, The issue was that the entire mac address was not being read in to generate the id.
David...here is the new pull request. I'm still not sure how we can test this bug fix.
=> Fixes unique server_id within my.cnf Ticket/MODULES-2675

manifests/backup/mysqlbackup.pp, manifests/backup/xtrabackup.pp
The weekday attribute of cron resource will be parse to negetive integer
with future parser. This patch is aim to ensure that the value types of
cron resouce are valid with future parser.
JIRA issue: https://tickets.puppetlabs.com/browse/MODULES-2787
=> (MODULES-2787) Fixes for future parser

templates/mysqlbackup.sh.erb
Using env variable causes acceptance test failure.
=> Use temp cnf file instead of env variable.

README.md, lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_datadir/mysql.rb, lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_datadir.rb, manifests/params.pp, manifests/server/installdb.pp, spec/classes/mysql_server_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
- Added MySQL version and flavour detection support
- Added mysql_datadir provider/type (replaces Exec[mysql_install_db])
- Added version specific parameters my.cnf ([mysqld-5.X] sections)
- Version specific user mangement SQL (ALTER USER for 5.7.6++ ...)
Rebased-By: David Schmitt <david.schmitt@puppetlabs.com>
=> Fixed MySQL 5.7.6++ compatibility

manifests/server/service.pp
If you set service_manage => false, because your instance of mysql is not managed by any service management OR in my case I'm only using this puppet module to manage mysql users, puppet generates an error.
Error: /Stage[main]/Mysql::Server::Service/Service[mysqld]: Could not evaluate: Could not find init script or upstart conf file for 'mysql'
=> Fixing error when disabling service management and the service does not exist

manifests/server/service.pp
The old mysql init scripts waited till mysql was up and running till they finished. With ubuntu 14.04 and upstart (re)starting mysql will no longer wait for mysql to finish starting up. So in some cases, puppet will try to run mysql queries against the mysql server which is still starting up.
This patch prevents that by waiting till the configured mysql socket is available if the mysql service gets updated.
=> ensure if service restart to wait till mysql is up

manifests/server/service.pp
When service in not managed, this kind af errors appears:
Error 400 on SERVER: Could not find resource 'Service[mysqld]' for relationship from 'File[mysql-config-file]'
=> Move all dependencies to not have them in case of service unmanaged

spec/classes/mycnf_template_spec.rb, templates/my.cnf.erb
Prior to 136b1aa646efde57b91fd994bfcf55b38ba7c294 it was possible to
have an empty string as value of a my.cnf parameter, resulting in a line
with just the parameter name.
That commit re-enable that behavior that was removed by accident.
=> Re-Add the ability to set a empty string as option parameter

lib/puppet/provider/mysql_grant/mysql.rb
If a user exists in the database upon first Puppet run (for example, in the case of loading a database snapshot) and the run sets that user's :ensure attribute to 'absent', the mysql_grant provider will throw an error when the dependency chain causes it to try to destroy the grants associated with that user because the DROP statement from the mysql_user provider already removed the grants. To fix, we must check if the user exists before revoking the grants.
=> Fixes edge-case with dropping pre-existing users with grants

lib/puppet/provider/mysql_grant/mysql.rb
Change mysql_grant provider to ignore/delete double-quotes -- as it does with single quotes and backticks -- in the returned list of existing grants. With ANSI_QUOTES enabled in MySQL's sql_mode, grant identifiers (e.g. database name) are quoted with double-quotes rather than backticks, for example "foo".* vs. `foo`.*. This breaks mysql_grant's evaluation of existing grants and causes it to apply grants with every run.
=> (#3028) Fix mysql_grant with MySQL ANSI_QUOTES mode

templates/my.cnf.pass.erb
MySQL ecosystem has a lot of tools that use .my.cnf such as mysqldump or
mysqladmin. Generating all sections allows operator to use them under
root account without passing -p<password>
=> Generate .my.cnf for all sections

manifests/server/installdb.pp
Executing mysql_install_db with the defaults-extra-file set to the
global option file can produce errors with duplicates. For example it
happens when 'ignore-db-dir' option passed to $override_options in
mysql::server class. Same as https://bugs.mysql.com/bug.php?id=69441
=> Use mysql_install_db only with uniq defaults-extra-file

templates/mysqlbackup.sh.erb
Fixed problem with ignoring parameters from global configs
=> Fixed global parameters skipped

manifests/server.pp
When there is a new install, the package installation will run `mysqld
--initialize` or `mysql_install_db` which leaves `mysqld` in a running
state. If you have `$mysql::server::restart` set to false, `mysqld` will
not restart and you will be left in a state of running a default config
instead of your intended configuration.
=> Config before install

spec/spec_helper_acceptance.rb
The module is not really used, but its absence creates nasty warning
messages.
=> (maint) Add missing nanliu/staging module

manifests/params.pp
This ticket points out that the opensuse 12 configuration bails on a very simple manifest, so 12 should actually have the defaults that are currently set only for 13 and higher.
=> (MODULES-1256) Fix parameters on OpenSUSE 12

manifests/server/config.pp
Without this change installing mysql fails with the following errors on Debian and
Ubuntu:
Error: Cannot create /etc/mysql/conf.d; parent directory /etc/mysql does not exist
Error: /Stage[main]/Mysql::Server::Config/File[/etc/mysql/conf.d]/ensure: change from absent to directory failed: Cannot create /etc/mysql/conf.d; parent directory /etc/mysql does not exist
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/mysql/my.cnf20160413-2395-1uo3ffj.lock at 39:/etc/puppetlabs/code/modules/mysql/manifests/server/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/mysql/my.cnf20160413-2395-1uo3ffj.lock at 39:/etc/puppetlabs/code/modules/mysql/manifests/server/config.pp
Wrapped exception:
No such file or directory @ …
=> (FM-5050) Configure the base of includedir

lib/puppet/provider/mysql_datadir/mysql.rb, lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_datadir.rb, manifests/server/installdb.pp
This PR adds support for Percona 5.7. Percona Server is a superset of community mysql and essentially acts like it.
This PR will resolve MODULES-3193.
I notice that there is a tagged 3.7.0 release but the CHANGELOG.md still states "Supported Release 3.6.2". What are the plans to release and/or support 3.7.0?
=> Add support for Percona 5.7

README.md
Hi guys,
Great job on the module.
I was doing the tests to install Percona 5.7 on a Centos 7 box with this module as some people ask if it's doable.
The commit adds this case in the documentation to help the diversity of usage example as this one is pretty easy.
This should help the questions of #757
To have this working, you need to have #818 integrated to the repo.
Thanks for your time,
Joseph
=> Add documentation example for Perconna installation on Centos

manifests/backup/mysqldump.pp
The script used by this mysqldump class, mysqlbackup.sh, requires bzcat
which is part of the bzip2 package.
This patch will make sure that bzip2 is installed before setting up the
cron tab job using mysqlbackup.sh
=> Added bzip2 package support on mysqldump backup

lib/puppet/provider/mysql.rb
Default mysqld_type return value should be "mysql" if another type is not detected. Returning nil breaks mysql 5.7.11 on Ubuntu (at least) due to the conditional used in mysql_user provider.
=> Default mysqld_type should be "mysql"

lib/puppet/provider/mysql_datadir/mysql.rb
MySQL-server-advanced installs install the 'mysql' directory in /var/lib/mysql by default,
therefore the check fails and does not run mysql_install_db.
Check is adjusted to check if any files exist in the directory.
=> Check that /var/lib/mysql actually contains files.

lib/puppet/provider/mysql.rb
Since the default MySQL return type is 'mysql', only check for MariaDB and Percona specially.
=> Remove mysql regex when checking type

lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_grant/mysql.rb, lib/puppet/provider/mysql_user/mysql.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Change the behaviour of applying user and grant related changes to use the system database of MySQL.
This is a workaround to fix a bug in MySQL (https://bugs.mysql.com/bug.php?id=65923) that causes users and grants to be replicated, even if the "mysql" database should not be replicated.
=> (MODULES-2111) Add the system database to user related actions.

manifests/params.pp
On Debian, it's a good practise to use 'adm' for the group in logfiles: 
> adm: Group adm is used for system monitoring tasks. Members of this group can read many log files in /var/log
Most of the packages available are using it for the initial creation of the error.log and add an logrotate job which creates a new logfile with this group while rotating. Causing puppet to change the group after every logrotate.
=> default group for logfiles on Debian/Ubuntu should be adm

manifests/params.pp
There was an issue with the latest amazon linux release that would make the installation fail because of the fact verification on params.pp:
```
[root@AmazonLinux ~]# facter operatingsystem
Amazon
[root@AmazonLinux ~]# facter operatingsystemmajrelease
4
[root@AmazonLinux ~]# facter osfamily
RedHat
```
Because of this line of code:
`  if $::osfamily == 'RedHat' and $::operatingsystemmajrelease == '4'  {`
The module would exit with an error stating that the installation is not supported on RedHat older than major release 5 which in the case of the latest amazon linux is not true.
=> Fixed an issue with Amazon linux major release 4 installation

lib/puppet/provider/mysql_datadir/mysql.rb
On Gentoo, mysql_install_db script is installed into /usr/share/mysql/scripts
and therefore is not found by mysql_datadir type.
This commit adds scripts path to ENV['PATH'] so it can be found.
=> Support mysql_install_db script on Gentoo

manifests/server/installdb.pp, manifests/server/service.pp
Installation of Percona-Server-57 from yum repository has a side effect - touching of /var/log/mysqld.log. The file is empty and owned by root user, and that prevents mysql datadir initialization. 
puppet-agent[2003]: Execution of '/usr/sbin/mysqld --initialize-insecure --basedir=/usr --datadir=/var/lib/mysql --user=mysql --log-error=/var/lib/mysql/mysqld.log' returned 1
.
Given issue reproduced on CentOS 6.7, possibly on CentOS7.
=> move out $options['mysqld']['log-error'] from service.pp into installdb.pp

manifests/db.pp
The anchors create a dependency cycle if `mysql::client` must be installed before `mysql::server` and `mysql::db` resources are configured.
We are forced to use official mysql packages from http://repo.mysql.com. There the mysqladmin script is in the mysql client package. Therefore, that `mysql::server::root_password` can use mysqladmin, we added:
`Class[Mysql::Client] -> Class[Mysql::Server]`
this works as long as we don't configure any `mysql::db` resources. As soon as a `mysql::db` resource is defined the following dependency cycle exists:
`
Anchor[mysql::client::end] => Class[Mysql::Client] => Class[Mysql::Server] => Anchor[mysql::server::start] => Class[Mysql::Server::Config] => File[mysql-config-file] => Service[mysqld] => Class[Mysql::Server::Service] => …
=> remove erroneous anchors to mysql::client from mysql::db

lib/puppet/provider/mysql_datadir/mysql.rb
MySQL from CentOS SCL repository is installed in different location. You should also check for binaries in this location.
Without this change puppet returns error like: Could not find a suitable provider for mysql_datadir
=>  Find MySQL 5.5 installation on CentOS

manifests/params.pp
This is a rebase&squash of #841
=> Use mariadb by default for Debian Jessie

manifests/params.pp
This reverts commit af85cf7dfb1c3d0cab5b123cdf7ccfe40b7b90d3. It turned out to
be a very bad idea to change the defaults. To fix this in the long term, the
module needs to separate product/version selection from the OS-defaults. For now,
please supply those values through the main parameters to select mariadb.
=> Revert "Use mariadb by default for Debian Jessie (#845)"

templates/mysqlbackup.sh.erb
If mysqldump uses --defaults-extra-file mysql should use the same. Otherwise settings like different socket paths etc. will not work. Preferably this should be detected via test cases, as backups are quite important...
=> Fix global parameter usage in backup script

README.md, lib/facter/mysqld_version.rb, lib/puppet/provider/mysql.rb, spec/unit/facter/mysqld_version_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Per https://tickets.puppetlabs.com/browse/MODULES-3441, the mysql module has behaviour which varies by server version. The version is discovered by running `mysqld -V`. On hosts without a MySQL server package install, this fails, which means that contrary to the README, it's not actually possible to use this module to manage a remote db.
This PR moves the version string discovery into a new fact, `mysqld_version` which is used by the provider.  This makes it possible to configure the db version with a custom fact when a remote db (eg AWS RDS) is being managed.
=> [MODULES-3441] Discover mysql version using facts

manifests/server/account_security.pp
if server don't have domain name facter don't initialize fqdn and mysql_user resource fails with "...Invalid database user..." error.
=> Resource fails when fqdn is not set.

metadata.json
Staging 2.0.0 has dropped ruby 1.8.7 support only. All tests are run against the head of puppet/staging already.
=> Support for puppet/staging 2.0.0

README.md, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp, spec/classes/mysql_server_backup_spec.rb, templates/mysqlbackup.sh.erb
Add maxallowedpacket parameter for the puppetlab mysql module backup dump script. Feature request:  https://tickets.puppetlabs.com/browse/PUP-6404 The default value is 1MB as it is default for Mysql.
=> add new backup dump parameter maxallowedpacket

README.md
Hi,
As I've seen quite often questions on how you install a MariaDB server on Ubuntu, I decided to add an example to the documentation.
I've tested this minimal example on an Ubuntu Trusty server and it worked.
Thanks for the reviews.
Joseph
=> Add example of MariaDB server installation on Ubuntu

manifests/backup/xtrabackup.pp, manifests/params.pp
This is a new pull request as the previous one could not be squashed before fixing the conflict.
=> parametrize xtradb package name

lib/facter/mysql_server_id.rb, spec/unit/facter/mysql_server_id_spec.rb
MySQL server ID requires a value that is less than 2^32. With the current server-id generation it's possible to get a value that exceeds this limit. Reference the following documentation: 
– https://dev.mysql.com/doc/refman/5.7/en/replication-options.html#option_mysqld_server-id
I have provided an example of the fix below: 
```ruby
irb(main):002:0> x = ['ff','ff','ff','ff','ff','ff'][2..-1].inject(0)
{ |total, value| (total << 6) + value.hex }
=> 67907775
```
```ruby
irb(main):003:0> x < 2**32
=> true
```
See bug report here: https://tickets.puppetlabs.com/browse/MODULES-3711
=> MODULES-3711 - Add limit to mysql server ID generated value

README.md, lib/puppet/provider/mysql_grant/mysql.rb
hello,
while trying to implement some basic stuff on mysql/identity management (account lifecycle present,disabled,absent) I came across on a not nice behavior. If user is ever granted a granting option, those cannot be revoked in a fine manner. the "feature" itself is not documented because it's more like side effect.
testcase:
1. mysql_grant( ... options=>['GRANT'])
2. grant is present
3. mysql_grant( ... options=>[])
3a. mysql_grant( ...)
4. grant is present
5. mysql_grant( ... options=>"")
6. grant is revoked
7. mysql_grant( ... options=>"")
8. grant is revoked again
... its revoked everytime
This patch proposes a more proper handling options attribute on grant resource. Initialize option everytime even if it's not present, NONE keyword is not honored in providers cmd_options, so it …
=> revoking GRANT privilege fix

lib/puppet/type/mysql_grant.rb, lib/puppet/type/mysql_user.rb
User name length has changed "MySQL user names can be up to 32 characters long (16 characters before MySQL 5.7.8)"
see http://dev.mysql.com/doc/refman/5.7/en/user-names.html
Tested on CentOS release 6.8 (Final) with mysql version 5.7.14
=> MODULES-3697 Changed puppet fail behaviour for mysql create user and grant if user name is longer than 16 chars

manifests/server/installdb.pp
In the case that the Puppet manifest has
```puppet
File {
mode => '0444',
}
```
this will be inherited and render the log file unwritable, unless we specify mode.
=> Ensure that error log is writable by owner

lib/facter/mysqld_version.rb, spec/unit/facter/mysqld_version_spec.rb
Currenly performing a `puppet apply`, the following output is shown
```
Info: Loading facts
160903 16:55:09 [Note] /usr/sbin/mysqld (mysqld 10.0.26-MariaDB-0+deb8u1) starting as process 6358 ...
Notice: Compiled catalog for foo.example.com in environment production in 1.52 seconds
```
This is due to Facter performing `mysqld -V` to determine the version as fact.
The output of this command alone is this:
```
$ sudo mysqld -V
mysqld  Ver 10.0.26-MariaDB-0+deb8u1 for debian-linux-gnu on x86_64 ((Debian))
160903 17:02:08 [Note] mysqld (mysqld 10.0.26-MariaDB-0+deb8u1) starting as process 7260 ...
```
Where the line with 'starting as process' is STDERR.
This diff redirects STDERR to /dev/null, since it probably contain any critical information (during a version check). 
After applying this …
=> Silence STDERR in Facter

manifests/params.pp
As in [this ticket](https://tickets.puppetlabs.com/browse/MODULES-3557), Ubuntu 16.04
package names for language bindings are not present in manifests/params.pp, incurring errors
when using the module.
This pull request adds an additional case ('xenial') for the
ruby_package_name parameter in the 'Debian' case, so as to avoid falling
through to the default case. A conditional block for the
php_package_name parameter in the 'Debian' case has also been added, so
as to allow for correct package name usage on 16.04, whilst maintaining
backwards-compatibility with the default case.
=> [MODULES-#3557] Add Ubuntu 16.04 package names for language bindings

lib/puppet/provider/mysql_datadir/mysql.rb
Please review the following ticket. 
https://tickets.puppetlabs.com/browse/MODULES-3907
Puppetlabs/mysql does not run --insecure-initilize if the datadir does not contain the mysql directory. The module fails on a fresh MySQL / Percona 5.7 deploy.  
I have reviewed the logic, and don't see anything that would actually run the initialize command. 
After adding the initialize command to the 5.7 block, the deploy is successful, and only runs if the $data_dir/mysql does not exist. 
```
==> integration-7: Notice: /Stage[main]/Mysql::Server::Installdb/File[/var/log/mysql/mysqld.err]/ensure: created
==> integration-7: Debug: /Stage[main]/Mysql::Server::Installdb/File[/var/log/mysql/mysqld.err]: The container Class[Mysql::Server::Installdb] will propagate my refresh event
==> integration-7: …
```
=> MODULES-3907 Add MySQL/Percona 5.7 initialize on fresh deploy

README.md, lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_grant/mysql.rb, spec/acceptance/types/mysql_grant_spec.rb
Basic support for REQUIRE SSL or REQUIRE X509 only through the options param on the mysql_grant type. This seems like an option we should support.
It would be nice to support any option in the options array, but I'm not sure about the code to check if the options are set in the instances method. Seems like you need to look for something explicitly in the rest, the way it is set up currently.
=> Add support for REQUIRE SSL|X509 option

README.md, manifests/db.pp, spec/defines/mysql_db_spec.rb
Added parameter import_cat_cmd to specify the command to read sql files. Usefull for compressed sqlfiles
See: https://tickets.puppetlabs.com/browse/MODULES-3879
=> Added parameter import_cat_cmd

manifests/params.pp
This fixes the following error which occurs during usage on ubuntu 16.04:
Debug: Executing '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-mysql'
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install php5-mysql' returned                                                                                                                       100: Reading package lists...
Building dependency tree...
Reading state information...
Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php5-mysql' has no installation candidate
/usr/lib/ruby/vendor_ruby/puppet/util/execution.rb:219:in `execute' …
=> fixes problem with package name change from php5-mysql to php-mysql on 16.04

README.md, lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_grant/mysql.rb, spec/acceptance/types/mysql_grant_spec.rb
Reverts puppetlabs/puppetlabs-mysql#888
This is not valid on mysql 5.7:
```
mysql> SHOW WARNINGS; GRANT ALL ON `test`.* TO test3@tester REQUIRE SSL;
+---------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                            |
+---------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1287 | Using GRANT statement to modify …
```
=> Revert "Add support for REQUIRE SSL|X509 option"

README.md, lib/puppet/provider/mysql_user/mysql.rb, lib/puppet/type/mysql_user.rb, spec/acceptance/types/mysql_user_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
This adds support for adding or modifying tls options via the
mysql_user provider. this works with newer mysql syntax which uses
the ALTER USER syntax and also with the older syntax which relies on
using GRANTs.
=> Add support for setting tls options for mysql_user's

templates/mysqlbackup.sh.erb
We want to have an easy way to check whether the backup was successful. In my opinion adding a simple flag file is the easiest and universally usable method.
To check whether the backup was successful, we will simply check whether the last modification of the file was longer than the defined backup interval. Such a test can very easily be integrated in most monitoring solutions.
=> Add a file in /tmp to check when the last backup was successful

README.md, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp, spec/classes/mysql_server_backup_spec.rb, templates/xtrabackup.sh.erb
This PR will bring the `xtrabackup` provider up to par with the `mysqldump` provider and adds one other enhancement:
- Add support for existing parameters `$backupuser` and `$backuppassword`
- Automatically create backup user/grants
- Add support for the `databases` parameter to provide a list of databases to back up
- Add support for optional arguments to `innobackupex` by adding the new parameter `$optional_args`
This makes it possible to specify additional arguments to be passed to `innobackupex`:
```
mysql::server::backup:
provider: 'xtrabackup'
user: 'backupusr'
password: 'secret'
databases:
- 'foo'
- 'bar'
optional_args:
- '--no-lock'
- '--parallel=2'
```
=> Enhancements to xtrabackup backup provider

lib/puppet/provider/mysql_datadir/mysql.rb
Our update to 3.10.x broke the solaris support. This adds possible search paths for mysqld and mysql_install_db.
Thanks
Oliver
=> add solaris 11 paths to provider

lib/puppet/provider/mysql_user/mysql.rb
Fixing this error:
Could not autoload puppet/provider/mysql_user/mysql: /var/lib/puppet/lib/puppet/provider/mysql_user/mysql.rb:39: syntax error, unexpected ')'
/var/lib/puppet/lib/puppet/provider/mysql_user/mysql.rb:197: syntax error, unexpected $end, expecting kEND
=> Fix trailing comma syntax error

README.md, manifests/server/mysqltuner.pp
Extend mysql::server::mysqltuner with an $environment, which is then passed onto staging::file, so that a proxy variable can be passed that allows mysqltuner to be downloaded. Example usage.
```
class { 'mysql::server::mysqltuner':
environment => 'https_proxy=http://myproxy.example.ch:80',    # for download
}
```
=> Allow mysqltuner to be downloaded via a proxy

manifests/backup/mysqldump.pp
We don't need bzip2 unless backupcompress
=> Only install bzip2 if backupcompress

lib/puppet/provider/mysql_grant/mysql.rb, lib/puppet/type/mysql_grant.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/unit/puppet/type/mysql_grant_spec.rb
The mysql_grant type does not currently support PROXY grants. The only real difference between PROXY and other grants is that the "table" is actually a user (proxy_user@proxy_host). This patch adds this support and allows for the following:
```puppet
mysql_grant { 'foo@bar/baz@blah':
ensure     => present, # or absent
user       => 'foo@bar',
table      => 'baz@blah',
privileges => 'PROXY',
}
```
=> (#4534) Add PROXY grant support to mysql_grant

lib/puppet/type/mysql_grant.rb, spec/acceptance/types/mysql_grant_spec.rb
I merged PR #934 and it failed CI for older mysql versions because PROXY privileges are not supported until mysql version 5.5.0. Rather than revert this functionality I have added validation to the mysql_grant type and also added an  acceptance test to test for this error.
All PROXY tests within mysql_grant type have been placed in their own describe block where pre_run is called and retrieves the mysql version from the SUT. The remaining PROXY tests are filtered on this musql version to ensure they do not run on mysql versions < 5.5.0
=> (maint) Fail when proxy privilege added on mysql version < 5.5.0

README.md
This is prepping the README for translation. Work carried out include
the following:
Values true, false, undef must be wrapped in backticks.
Strings must always be in single quotes.
Sentences must not contain hard returns; they cause the translation
software to create new paragraphs.
For code blocks, use triple backticks (```) and the name of the
language. Without language highlighting, the backticks get stripped out.
Also, language highlighting is nice.
Standardize exceptions to default values (for example, Default value:
'/etc/ntp.conf' (Solaris: '/etc/inet/ntp.conf').)
=> (Modules-4320) Readme update for i18n Process

manifests/server/installdb.pp
(MODULES-4743) puppetlabs-mysql : cannot initialize database dir not empty
=> (MODULES-4743) mysql : cannot initialize database dir not empty

manifests/params.pp
The error I was getting was:
```
Error: Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at '/puppetlabs-mysql/manifest/params.pp'....
```
Puppet 4 introduces strong type checking so after this change it will work on puppet 4 and puppet 3
from
`if versioncmp($::operatingsystemmajrelease, '14.10') > 0 {`
to
`if versioncmp("${::operatingsystemmajrelease}", '14.10') > 0 {`
=> versioncmp parameter compatibility

lib/puppet/type/mysql_grant.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/unit/puppet/type/mysql_grant_spec.rb
Users are running into an issue where \`puppet resource mysql_grant\` fails because there is a global name validation using properties that only exist in a compiled catalog and not in the naked type that is instantiated during a \`puppet resource\` run. self[:user] and self[:table] are nil in this use case so there is a failure. This commit surrounds the validation in an if statement so it is not called during \`puppet resource\`. Also, a happy path test is added and the acceptance test is removed."
=> (MODULES-4604) move name validation in mysql_grant type

README.md
This minimal example shows how to install MySQL Community Server 5.6 on Centos 7.3 using Puppet 3.8.7 using hiera and puppet-mysql=3.9.0
Should clarify why #757 does not really make sense, also should help people with fully working example without needing to read about Percona example ;)
=> Add example how to install MySQL 5.6 on CentOS 7

spec/classes/graceful_failures_spec.rb
Due to https://github.com/mcanevet/rspec-puppet-facts/pull/53 some of our unti tests are failing
on Travis. This fix averts these errors for the meantime while still running the same test.
=> Fix to get Travis running green on unit tests

manifests/backup/xtrabackup.pp
With empty strings the template has the --user and --password options, but those are empty.
=> Fixing empty user/password issue

README.md
Fixed capitalization of Hiera because I was worried it might throw the translators off.
Also removed a bit of unnecessary white space.
=> (MODULES-5280) fix capitalization in README

lib/puppet/type/mysql_datadir.rb, lib/puppet/type/mysql_grant.rb, lib/puppet/type/mysql_user.rb
This is triggering PUP-7925, causing the mysql module being unusable on
all existing puppet versions.
=> (MODULES-5602) remove superfluous backslashes from regular expressions

spec/spec_helper_acceptance.rb
the name of the install_language_pack function has changed to install_language_pack_on, this updates it in spec_helper_acceptance
=> (maint) install language pack method

Gemfile, metadata.json, spec/acceptance/locales_spec.rb, spec/spec_helper_acceptance.rb
Prior to this commit, our i18n gems were being installed from git
as they were not yet released. Now that they've been released,
just install them from RubyGems.
_This PR is queued up in advance but shouldn't be merged until all the gems have been released._
=> (FM-6362) Install i18n gems from RubyGems

spec/spec_helper_acceptance.rb
the latest version of the i18n_helper changes install_language_pack_on to install_language_on so this makes that change in spec_helper_acceptance. it also removes sudo from a couple host commands in the same file to resolve an error i was getting there
=> (maint) update install_language_pack_on method

metadata.json
db51029d27279e7e4ce46a8ceb61f2e6089aa2c4 added support for Stretch but didn't add this to the metadata.
=> List Debian Stretch as supported

lib/puppet/provider/mysql_grant/mysql.rb
This fixes a typo in the mysql_grant provider. (and sorry for the 2 commits it took to do that, not used to working via github)
=> Corrects a typo in the mysql_grant provider

spec/spec_helper_acceptance.rb
Currently task setup is trying to run on LTS which causes failures as it
is not supported.
=> Do not run task setup on LTS

spec/classes/mysql_server_spec.rb, templates/my.cnf.erb
https://tickets.puppetlabs.com/browse/MODULES-3168
If set `bind-address` to `undef` the bind-address will not be set in the mysql-config file so MySQL is listening on all interfaces.
```puppet
class { '::mysql::server':
override_options => {
mysqld => {
bind-address => undef,
},
}
```
=> #puppethack allow undef value for bind-address

tasks/export.json, tasks/export.rb
This commit simply adds export database task to the local file using Bolt.
=> Add Export database task

lib/puppet/provider/mysql.rb, spec/acceptance/types/mysql_grant_spec.rb
Fixes [MODULES-2075](https://tickets.puppetlabs.com/browse/MODULES-2075).
=> Add support for `GRANTS FUNCTION`

lib/puppet/provider/mysql_user/mysql.rb, spec/acceptance/types/mysql_user_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Currently changing the `plugin` property of the `mysql_user` resource has no effect.
=> Allow authentication plugin to be changed

CHANGELOG.md
A puppet classname has 2 colons (:) in its name.
=> (maint) Fix a typo in a classname in the changelog

manifests/server.pp, spec/acceptance/mysql_server_spec.rb
Currently this module requires two executions of `puppet apply` to properly configure MySQL. On an Ubuntu 16.04 instance, I am seeing the second Puppet run produce the following changes:
```
Notice: Compiled catalog for ubuntu-16.04-x64 in environment production in 1.93 seconds
Info: Applying configuration version '1504824440'
Info: Computing checksum on file /etc/mysql/conf.d/mysql.cnf
Info: /Stage[main]/Mysql::Server::Config/File[/etc/mysql/conf.d/mysql.cnf]: Filebucketed /etc/mysql/conf.d/mysql.cnf to puppet with sum c992f7b57d778f607e8d83792936e92b
Notice: /Stage[main]/Mysql::Server::Config/File[/etc/mysql/conf.d/mysql.cnf]/ensure: removed
Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}59e52aeed142f9004c9e74ff5e4f1d84'
Info: …
```
=> Ensure that Puppet runs are idempotent

lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_datadir/mysql.rb, lib/puppet/provider/mysql_user/mysql.rb
Also centralized the version checking conditional.
CC #942
=> (MODULES-7198) Fix DROP USER IF EXISTS on mariadb

manifests/server/backup.pp, templates/mysqlbackup.sh.erb
Tests not needed. Rebases and closes #938
=> Support for optional__args and prescript to mysqldump backup provider

examples/mysql_user.pp, lib/puppet/functions/mysql/deepmerge.rb, lib/puppet/functions/mysql/dirname.rb, lib/puppet/functions/mysql/password.rb, lib/puppet/functions/mysql/strip_hash.rb, lib/puppet/parser/functions/mysql_deepmerge.rb, lib/puppet/parser/functions/mysql_dirname.rb, lib/puppet/parser/functions/mysql_password.rb, lib/puppet/parser/functions/mysql_strip_hash.rb, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/db.pp, manifests/server.pp, manifests/server/binarylog.pp, manifests/server/config.pp, manifests/server/monitor.pp, manifests/server/root_password.pp, spec/functions/mysql_deepmerge_spec.rb, spec/functions/mysql_dirname_spec.rb, spec/functions/mysql_password_spec.rb, spec/functions/mysql_strip_hash_spec.rb
The legacy puppet3 functions-api should be avoided.
This migrates the existing functions to the new api and uses it in the module. It also adds the tests for the new functions based on those for the olds when they existed.
We should keep the legacy functions for now to allow compatibility for those using the functions outside out this module.
=> Use puppet4 functions-api

manifests/backup/xtrabackup.pp, manifests/db.pp, spec/defines/mysql_db_spec.rb
Adding some additional options we like to set on mysql::db
=> Add user tls_options and grant options to mysql::db

.gitignore, .pdkignore, .rubocop.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, metadata.json, spec/acceptance/locales_spec.rb, spec/acceptance/mysql_backup_spec.rb, spec/acceptance/mysql_helper.rb, spec/acceptance/mysql_server_spec.rb, spec/acceptance/sql_task_spec.rb, spec/acceptance/types/mysql_database_spec.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/acceptance/types/mysql_plugin_spec.rb, spec/acceptance/types/mysql_user_spec.rb, spec/spec_helper.rb, spec/spec_helper_acceptance.rb, spec/unit/puppet/provider/mysql_database/mysql_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Implementing `beaker-testmode_switcher` in this module allows us to test in a more realistic method and more like how customers use puppet as a tool. 
When there is an agent only setup this module will continue to use `puppet apply <manifest>` however where there are masters present the manifest will now be injected onto the master and agents will run `puppet agent --test`. 
This will give us the capability of testing the master agent integration and ensure that all information and settings are sent over as expected. This will also allow us to ensure scenarios like the following do not reoccur: https://tickets.puppetlabs.com/browse/PUP-8026
=> (MODULES-7439) - Implementing beaker-testmode_switcher

.travis.yml
Currently we are seeing Ubuntu14 failures related to https://tickets.puppetlabs.com/browse/PUP-9008 which was released in puppet-agent 5.5.3. In order to remove our road block this fix is a temporary work around.
This change has been put directly into the travis.yml file, therefore if forgotten about it will be removed on the next pdksync as this change was not put into the templates. 
The following PR has been created to resolve the issue however we are pinning the `BEAKER_PUPPET_AGENT_VERSION` until this change has been released: https://github.com/puppetlabs/puppet/pull/6950
=> (PUP-9008) - Temporary workaround for Puppet `upstart` Bug

spec/spec_helper_acceptance.rb
Changed comparison of versions from default string comparisons to Gem::Version as the string comparisons use lexicographical ordering which can fail on certain cases e.g. '4.10.5' > '4.10.12' resolves to true which is incorrect as 4.10.12 is a later version than 4.10.5 .
=> (maint) - Change versioning comparison

lib/puppet/provider/mysql_user/mysql.rb
Since [MariaDB 10.2.16](https://github.com/MariaDB/server/commit/5f0510225aa149377b8563f6e96b74d05d41f080), the `SET PASSWORD` command stores user passwords in the `mysql_native_password` plugin `authentication_string` instead of in the `password` column of `mysql.user`.
The module checks the `password` column instead of the `authentication_string` on all versions of MariaDB. In every Puppet run involving MariaDB 10.2.16 and newer, the module attempts to update
managed user passwords even when they haven't changed (`Notice: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/password_hash: changed password`) because the `password` field is always empty.
Update the if statement to check the plugin authentication string on MariaDB 10.2.16 and newer.
See also MariaDB JIRA …
=> (MODULES-7487) Check authentication string for user password on MariaDB 10.2.16+

lib/puppet/provider/mysql_user/mysql.rb, manifests/params.pp
MySQL 8 doesn't support "... IDENTIFIED BY PASSWORD ..." syntax  and resources options (used after WITH in GRANT command) were moved from GRANT to ALTER USER.
If plugin is ommited, 'mysql_native_password' plugin is used by default (because the default MySQL 8 user plugin is 'caching_sha2_password')
=> MySQL 8 compatibility in user management

lib/puppet/provider/mysql_user/mysql.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Support user creation on galera. Add IF NOT EXISTS to CREATE USER in mysql_user provider
Description of issue in jira - https://tickets.puppetlabs.com/browse/MODULES-7857
=> (MODULES-7857) Support user creation on galera

manifests/params.pp
While using MySQL 8.0, the configuration options in the mysqld params section had `query_cache_limit` and `query_cache_size` variables which are no longer supported for MySQL >= 8.0
Moving these into the version-specific hashes, rather than the `mysqld` default hash.  I didn't love having to duplicate those entries, but it does follow the same pattern of the `myisam-recover` option. 🤷‍♂️ 
This results in MySQL 8.0.12 actually starting up, rather than throwing the following error example:
```
[ERROR] [MY-011071] [Server] unknown variable 'query_cache_limit=1M'
```
=> Removing query_cache ops that are no longer supported in MySQL >= 8.0

manifests/params.pp
This breaks otherwise for setups using STRICT_VARIABLES=yes
=> Add includedir for Gentoo

manifests/params.pp
mysql::bindings::python installs the package set by the
python_package_name variable, which is 'MySQL-python' by default
on all RHEL and Fedora-based systems. This is no longer valid for
RHEL 8, since there is no Python3 support for the package.
In RHEL 8, we should use python3-PyMySQL instead.
=> [MODULES-8779] Set proper python_package_name for RHEL/CentOS 8

lib/puppet/provider/mysql.rb
Removing these as they were added back into the code by accident.
Original removal: https://github.com/puppetlabs/puppetlabs-mysql/pull/1064/files
Added back by: https://github.com/puppetlabs/puppetlabs-mysql/pull/1061/files
=> (MODULES-6627) Remove unused --host flags from mysqlcaller

templates/xtrabackup.sh.erb
Update to xtrabackup:
- set -o pipefail: failed piped command will give a success (pipe worked fine).
- copied the cleanup bits from from the mysqlbackup.sh.erb and the `mkdir -p $DIR`
=> Rotate option for xtrabackup script

manifests/server.pp
Hi,
Since release 5.4.0 MySQL package was install with default configuration, and after the configuration was set.
So we can not change innodb data size configuration for example (the default size is 12Mo and if you change this size MySQL can't be restart).
Someone have notify this conportement on the commit: https://github.com/puppetlabs/puppetlabs-mysql/commit/d13c06b9561d2c216bb9c5b48913ff2b4ac0b41b
I think it's better to rollback the ordering, and eventually change the resource `/etc/mysql/conf.d/mysql.cnf` in post-install class if it's needed
=> fix install ordering for innodb data size

CHANGELOG.md
The Changelog links assumed the version was tagged as `v8.1.0` while it is `8.1.0`
=> Fixed Changelog links for 8.1.0

manifests/backup/xtrabackup.pp, spec/classes/mysql_backup_xtrabackup_spec.rb, spec/classes/mysql_server_backup_spec.rb
Add a flag for activating or deactivating incremental backups. The
default is true so we don't change anything if you don't use the flag.
If the flag isi false we create a full backup every day instead of one
full backup and six incremental backups a week.
In addition, I outsourced the test of the mysql::backup::xtrabackup
class to test the additional parameters.
=> Make incremental backups deactivable

manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, spec/classes/mysql_server_backup_spec.rb
At this Time, this is not possible because a dupplicate resource error
occurs. With this change it is possible to generate a daily xtrabackup
and also a weekly mysqldump for example.
=> Allow multiple backupmethods

README.md
While checking the README to verify my next PR is according to the contribution guidelines, I noticed that the link to the contribution guidelines is broken.
This PR rectifies that issue.
=> Fix the contribution guide URL

lib/puppet/provider/mysql.rb, lib/puppet/provider/mysql_user/mysql.rb
The change introduced in mariadb 10.2.16 (and 10.3.8) where:
> the `SET PASSWORD` command stores user passwords
in the `mysql_native_password` plugin `authentication_string` instead of
in the `password` column
was addressed in https://github.com/puppetlabs/puppetlabs-mysql/pull/1135
This behaviour was short-lived.  In 10.2.19 and 10.3.11 the old
behaviour was restored.
> The fix in the commit dd6e74c62a2 made sure that the password field is always set, because that was the original issue that broke third-party tools.
See https://jira.mariadb.org/browse/MDEV-16774
This commit is based on
https://tickets.puppetlabs.com/browse/MODULES-6875?focusedCommentId=645260&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-645260
=> (MODULES-6875,MODULES-7487) - Fix mariadb mysql_user password idempotency

REFERENCE.md
Both mysqldump and mysqlbackup providers by default back up all databases in the database (i.e. when an empty array is specfied).
This patch documents that behavior.
See templates/xtrabackup.sh.erb and templates/mysqlbackup.sh.erb
=> Add note about default behavior of server backup

manifests/backup/mysqldump.pp, spec/classes/mysql_backup_mysqldump_spec.rb
This adds the missing time parameters to backup::mysqldump, thereby
allowing for backup frequency other than daily. It does not change
the other providers, and therefore does not change the documentation
of server::backup.
=> Allow backup::mysqldump::time to accept monthday, month, weekday

manifests/backup/xtrabackup.pp, spec/classes/mysql_backup_xtrabackup_spec.rb
Using Debian's default shell for cron (`/bin/sh`), the xtrabackup incremental cron was failing for me with an error message like:
```
Cron <root@foo> /usr/local/sbin/xtrabackup.sh --incremental-basedir=/foo/mysql-backups --target-dir=/foo/mysql-backups/`date +
/bin/sh: 1: Syntax error: EOF in backquote substitution
```
This is caused by  percent-signs (`%`) not being escaped. With `/bin/sh`, percent-signs (`%`) in the command, unless escaped with backslash \, will be changed into newline characters, and all data after the first % will be sent to the command as standard input. Thus the EOF error.
I also made another small commit to convert backtiks (`) into $(), which is the prefered POSIX way. https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03 has a …
=> Fix errors for /bin/sh with the xtrabackup cron

manifests/server/installdb.pp
Change relationship between the log-error file and the mysql datadir.  In FreeBSD this file needs to be present before trying to create the datadir and running the initdb step but will only be created if the option exists.
We should probably also have a require on the log-error file resource for `Package[ $mysql::server::package_name ]` so that the `user` and `group` are present, however, this is probably ensured by the chaining elsewhere.
=> Fix/fix dependency issue in freebsd with log error file creation from 10.0.0

manifests/params.pp
$::operatingsystemrelease is not equal to an "int" number.
We must use $::lsbdistcodename.
=>  Bugfix on Debian 9 : ruby_package_name must be ruby-mysql2

manifests/backup/mysqldump.pp
With FreeBSD bzip2 as part of the system, so it's not need to install
bzip2 package, and because this package doesn't exist the class go in
error if it try to install that package.
I put the change inside the mysqldump.pp I'm pretty sure that's not the correct way to do it (should be inside params.pp) but well I think it's the only os who have this difference, and...soon we going to use some hiera.yaml instead of this params.pp :wink:
=> No package under FreeBSD

manifests/server/backup.pp
The server::backup class don't use the correct information from
mysql::params about backupdirgroup. Because on FreeBSD the group root
doesn't exist it should use wheel instead. This difference are
correctly configure inside mysql::params but not inside server::backup
=> Fix group on FreeBSD

REFERENCE.md, lib/puppet/type/mysql_grant.rb, spec/unit/puppet/type/mysql_grant_spec.rb
I don't understand why the restriction on name is there at all but as long as it is it should be noted in the documentation.
=> Repair mysql_grant docs and diagnostics

Gemfile, metadata.json
This PR is the result of a `pdk update` to ensure that [this change](https://github.com/puppetlabs/puppetlabs-mysql/commit/0813f47bf8709526697d2cd88c0a99301f6666a3) is reverted and the module points to the latest released version of `pdk` now.
=> PDK Update to remove PDK-1525 workaround

lib/facter/mysql_version.rb
The custom fact should only run when mysql can be found within the PATH environment variable.
=> (MODULES-10114) Confine fact for only when mysql is in PATH

spec/unit/facter/mysqld_version_spec.rb
The fact being confined, no value was returned when mysqld was not
found.  Also stub the which method to fix the problem.
=> Fix test suite when mysqld is not installed

manifests/params.pp
Debian 10 does not have `libmysql-java`, it's actually `libmariadb-java`. Also the Ruby package name matches Debian 9.
=> Fix java and ruby binding packages for Debian 10

.travis.yml
Provisioning of CentOS 8 images using Docker, appears to be failing: https://travis-ci.org/puppetlabs/puppetlabs-mysql/builds/623152079 
Encountered this locally too when provisioning via Docker, however, this may be a different issue where `rpm --rebuilddb` was failing on new containers: https://bugzilla.redhat.com/show_bug.cgi?id=1680124. I ran with a [provision task that disabled `rpm --rebuildb`](https://github.com/puppetlabs/puppetlabs-mysql/pull/1268) - this worked locally, but **NOT** on Travis.
Further investigation and RCA is still required. In order to bypass a release blocker, we should disable the tests running on CentOS 8 and then re-enable when we have determined the root cause of the provisioning issue.
=> (FM-8784) Back out CentOS 8 from Travis CI tests

README.md, locales/puppetlabs-mysql.pot, manifests/server.pp, manifests/server/binarylog.pp, manifests/server/config.pp, manifests/server/installdb.pp, manifests/server/root_password.pp, manifests/server/service.pp, spec/classes/mysql_server_spec.rb, types/options.pp
This PR enables you to either use:
* `override_options` as it was the case previously. Those options are merged with the default options
* `options`. Those options won’t be merged with the default options.
Both are mutually exclusive in usage, meaning that one of them has to be empty.
I wrote this PR because we want to get rid of the version specific configuration options as it makes our workflows for changes of default parameters in our profiles easier.
I wrote it like this so that it has clean semantics: 
* override_options tells you that defaults are overridden
* options tells you that options will be set
Therefore, this PR is fully backwards compatible.
=> Enable module to not use default options

manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/mycnf_template_spec.rb
Sometimes more restrictive file-permissions on the MySQL configuration file are required.
e.g. in case of a Galera cluster, where you need to store `wsrep_sst_auth` credentials in the configuration. In that specific case it's a rather powerful MySQL user and you do not want the file to be be world-readable then.
It would be great if we can support this with _puppetlabs-mysql_ too.
PS: In respect of #32, where it was changed from a restrictive permission to `0644`.
=> Allow adapting MySQL configuration file's permissions mode

manifests/params.pp, manifests/server.pp, manifests/server/config.pp, spec/classes/mycnf_template_spec.rb
With my PR #1278 it's now possible to change the file-permission-mode of the mysql-config-file - _e.g._ `my.cnf`.
If you are trying now to apply a rather strict file-mode like `0600` - in combination with Puppet's default file-ownership `root:root` - it will lead to issues with MariaDB not being able to access the config-file after it has switched the processes to the service-user (_e.g._ `mysql`).
Therefor I would propose additionally using `$mysql::server::mysql_group` as the mysql-config-file's group-ownership. Then restricting access would be easy done with a `0640` file-mode.
=> Allow changing the mysql-config-file group-ownership

manifests/params.pp, manifests/server.pp, manifests/server/config.pp, manifests/server/managed_dirs.pp
On Ubuntu/Debian Puppet will fail if specifying path for:
```
tmpdir
basedir
datadir
innodb_data_home_dir
innodb_log_group_home_dir
innodb_undo_directory
innodb_tmpdir
```
deb packages starts mysql service automatically after install with the config provided by Puppet but will fail if the directory has not been created. Creating the directory should be part of the installation process.
A solution, less than ideal, is to create the folders (exec) and make them world readable. Then after the package has been installed (and user created) is to fix the permissions and ownership.
If anyone can come up with a more elegant solution...
Has been tested on:
Puppet 6.0.4 + Ubuntu 16.04LTS
=> Fix binarylog by allowing users to specify managed directories

lib/puppet/provider/mysql_user/mysql.rb, spec/acceptance/types/mysql_user_spec.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
Recent MariaDB versions provide a new authentication mechanism [1] based
on ed25519 [2]. It has been designed to be more secure than the native
SHA-1 based authentication [3]. 
Add the ability to configure all mysql users to require authenticating
to the server via mariadb's ed25519 auth plugin [1], rather than the
default native authentication [3].
[1] https://mariadb.com/kb/en/authentication-plugin-ed25519
[2] https://ed25519.cr.yp.to/ed25519-20110926.pdf
[3] https://mariadb.com/kb/en/authentication-plugin-mysql_native_password
=> Support mariadb's ed25519-based authentication

lib/facter/mysql_server_id.rb, spec/unit/facter/mysql_server_id_spec.rb
This uses the entire mac address then reduces the value to the
acceptable range for mysql.
=> Improve differences between generated mysql service id values

manifests/backup/mysqlbackup.pp
By default, `mysql::backup::mysqldump` and `mysql::backup::mysqlbackup` classes try to install cron-related packages.
This is pretty annoying, since it makes Puppet fail if any other package tries to do the same thing.
This PR adds a parameter (default: false) to be able to manage this.
=> Use ensure_packages() to install  the cron packages

manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp
Backup should only install cron, if one wants it.
based on this https://github.com/puppetlabs/puppetlabs-mysql/pull/1269
=> Handle cron package from different module

lib/puppet/provider/mysql_user/mysql.rb
As of MariaDB 10.4.1 the mysql.user table has been replaced by a view
onto the mysql.global_priv table, and the "UPDATE mysql.user" syntax
therefore no longer works.  Support for the newer ALTER USER statement
was added in MariaDB 10.2.0.
Fix the plugin attribute accessor to use ALTER USER for mariadb 10.2.0
or newer.  This matches the existing version check logic within the
password_hash and tls_options accessors.
Signed-off-by: Michael Brown <mbrown@fensystems.co.uk>
=> Use ALTER USER for mariadb 10.2.0 or newer

manifests/server.pp
A check for ascii characters revealed that the contraction for "do not"
was not a valid ascii character, this changes that.
resolves: https://tickets.puppetlabs.com/browse/MODULES-10723
=> Remove control character from manifests/server.pp

manifests/client.pp, manifests/client/install.pp, manifests/server.pp, manifests/server/install.pp, spec/classes/mysql_client_spec.rb, spec/classes/mysql_server_spec.rb
Hi,
I require this options for the commercial package. Oracle does not provide package repositories. We need to download the package and install with dpkg/rpm.
Test and validate on Ubuntu 18.04.
Regards,
=> add package provider and source

lib/puppet/provider/mysql.rb
In the rare event MySQL spits out something non printable this should cleanse it see the error below:
```
Error: Could not prefetch mysql_user provider 'mysql': invalid byte sequence in UTF-8
Error: Failed to apply catalog: invalid byte sequence in UTF-8
```
=> Remove non printable characters

spec/acceptance/mysql_backup_spec.rb
The latest version of Percona no longer supports Debian 8. Pinning to the last version that supported it.
=> (IAC-1175) Pin percona-release to version 1.0-22 for Debian 8 

spec/spec_helper_acceptance_local.rb
There are currently failures on Ubuntu/Debian images using Docker. This should resolve them.
=> (MAINT) Install curl package on Debian/Ubuntu

manifests/params.pp
The default python version on Ubuntu 20.04 is
python3 thus the current package is wrong.
This changes the package to use python3-mysqldb.
=> Fix package for python bindings on Ubuntu 20.04

manifests/server/managed_dirs.pp
Presumably the intention was to check that it is *both* not relative
and not already managed.
After update to 10.8 the mysql module tries and fails to manage '.'
on nodes where i have log-bin set to a relative path.
=> Repair check of logbindir

manifests/params.pp
FreeBSD uses MySQL 57 by default
Ref: https://svnweb.freebsd.org/ports/branches/2021Q1/Mk/bsd.default-versions.mk?revision=560000&view=markup#l83
=> Set default MySQL version for FreeBSD

manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp, spec/classes/mysql_backup_mysqldump_spec.rb, templates/mysqlbackup.sh.erb
This makes it possible to configure the previously hardcoded bzip2 compression and use a faster or parallel compression. It doesn't support package installation for other compression commands.
=> Support compression command and extension

.github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/pr_test.yml, .rubocop.yml, .sync.yml, .travis.yml, Rakefile, metadata.json
Remove Puppet 5 from testing and bump minimal version to 6.0.0
pdk version: `1.18.1`
=> pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0

metadata.json, spec/acceptance/types/mysql_login_path_spec.rb
The puppetlabs/resource_api module was used for puppet5 to install the
puppet-resource_api gem. With puppet6 and later this is not necessary
anymore.
=> Remove puppet5-specific resource_api module dependency

manifests/params.pp, spec/classes/mysql_backup_xtrabackup_spec.rb
Percona no longer includes the generic package name 'percona-xtrabackup' in their Ubuntu 20.04 focal fossa release of percona-xtrabackup. The package name 'percona-xtrabackup-24' must be used instead. This can be verified in the package names included by percona-release, listed at https://repo.percona.com/apt/dists/focal/main/binary-amd64/Packages
=> Update xtrabackup package name for Ubuntu 20.04

.puppet-lint.rc, lib/puppet/functions/mysql/password.rb, lib/puppet/functions/mysql_password.rb, lib/puppet/provider/mysql_user/mysql.rb, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/bindings.pp, manifests/bindings/client_dev.pp, manifests/bindings/daemon_dev.pp, manifests/db.pp, manifests/params.pp, manifests/server.pp, manifests/server/backup.pp, manifests/server/monitor.pp, manifests/server/root_password.pp, spec/classes/mysql_server_spec.rb, spec/functions/mysql_password_spec.rb, templates/my.cnf.pass.erb, templates/mysqlbackup.sh.erb, templates/xtrabackup.sh.erb
- fix some Puppetlint-Complaints, f.e. use Hash $::facts['blubb'] instead of specific global Variables
- let Function mysql::password accept Datatype Sensitive for Password
- let Function mysql_password accept Datatype Sensitive for Password
- add Parameter "sensitive" to Function mysql::password to decide if its Returnvalue should be of Datatype Sensitive
- add Parameter "sensitive" to Function mysql_password to decide if its Returnvalue should be of Datatype Sensitive
- let mysql_user accept Datatype Sensitive for  Parameter password_hash
- let mysql::backup::mysqlbackup accept Datatype Sensitive for Parameter $backuppassword
- let mysql::backup::mysqldump accept Datatype Sensitive for Parameter $backuppassword
- let mysql::backup::xtrabackup accept Datatype Sensitive for Parameter …
=> Use Puppet-Datatype Sensitive

lib/puppet/provider/mysql_user/mysql.rb
`GRANT USAGE` isn't acceptable on modern (8+) versions. There was fixes for some cases, I just add missed.
=> Fix mysql_user parameters update on modern MySQL

CHANGELOG.md, HISTORY.md
The top entry on the HISTORY.md file will be used as the since_tag if it
is not specified anywhere else. This is in relation to automatic change log generation.
=> (maint) Update the since_tag

lib/puppet/provider/mysql_grant/mysql.rb, spec/acceptance/00_mysql_server_spec.rb, spec/acceptance/01_mysql_db_spec.rb, spec/acceptance/04_mysql_backup_spec.rb, spec/acceptance/types/mysql_database_spec.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/spec_helper_acceptance.rb, spec/spec_helper_acceptance_local.rb
When the MySQL module is used against MySQL8, mysql_grant is no more idempodent.
This is because MySQL 8+ no more returns "ALL" for SHOW GRANTS, when all privileges
are granted. Instead, the separate privileges are shown.
Unfortunately, the tests were just adapted to not error in this situation.
This commit aims to fix the issue and also fixes the tests.
=> MODULES-8373 Fix mysql_grant resource to be idempodent on MySQL 8+

.github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/pr_test.yml, .github/workflows/spec.yml, .sync.yml, Rakefile, metadata.json
Debian had previously been removed in order to cancel the tests, however this can now be accomplished with the `exclude_platforms` parameter within the sync.yml
=> (IAC-1595) Return Debian to Metadata

lib/puppet/provider/mysql_user/mysql.rb
On a debian-11 server the plugin kept changing the password of a user. Turns out this user is using the plugin 'mysql_native_password', which does not use the PASSWORD field.
=> add mysql_native_password plugin to authentication_string vs password

lib/puppet/provider/mysql_grant/mysql.rb, spec/acceptance/types/mysql_grant_spec.rb
Currently every grant line stands for itself, this isnt corrent since MySQL can split these up into multiple GRANT statements. This change combines them before checking for diff
Fixes: https://tickets.puppetlabs.com/browse/MODULES-10856
All credits goes to https://github.com/fionera, just added a test.
=> Combine multiple grants into one while checking state

manifests/server.pp, manifests/server/config.pp
With the current code, if ssl-disable is set to true and restart is set to true, the notify message in the server::config class warning about ssl being disabled causes the service to be restarted on each Puppet run.
I have therefore moved that warning message outside of the server::config class, so that server::config ~> server::service does not trigger a restart of the service on each Puppet run.
=> Solve issue with repeated restarts if ssl-disable is true

.github/workflows/nightly.yml, .github/workflows/spec.yml, .puppet-lint.rc, .sync.yml, Rakefile, lib/facter/mysql_server_id.rb, lib/puppet/provider/mysql_grant/mysql.rb, manifests/backup/mysqlbackup.pp, manifests/bindings.pp, manifests/params.pp, metadata.json
(Maint) PDK Update
pdk version: `2.3.0`
=> pdksync - (Maint) PDK Update

manifests/params.pp, manifests/server/config.pp, spec/acceptance/00_mysql_server_spec.rb, spec/acceptance/01_mysql_db_spec.rb, spec/acceptance/04_mysql_backup_spec.rb, spec/acceptance/types/mysql_database_spec.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/spec_helper_acceptance_local.rb
Ran into numerous issues when Puppet attempted to install MySQL 8.0. Not sure if maybe the repos on Azure Ubuntu 20.04 are the problem but using MariaDB solved the issues.
=> Use MariaDB for Ubuntu 20.04

README.md, manifests/backup/mysqlbackup.pp, manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/params.pp, manifests/server/backup.pp, spec/classes/mysql_backup_xtrabackup_spec.rb
This is a fix for https://tickets.puppetlabs.com/browse/MODULES-11079
The current behavior of this module is to install the `percona-xtrabackup` package, even if we specify `mariabackup` as a backupmethod. This PR adds the `backupmethod_package` param, which allows users to specify the package needed for the backup binary (e.g. for mariabackup, you would specify the `mariadb-backup` package). An example is also provided in the README in this PR.
=> Add support for mariabackup 

manifests/params.pp
On Raspbian OS must be defined as provider 'mariadb', otherwise can not install mysql-agent
=> [Compatibility] Add Raspbian OS to provider configuration

manifests/backup/mysqldump.pp, manifests/backup/xtrabackup.pp, manifests/server/backup.pp, spec/classes/mysql_backup_mysqldump_spec.rb, templates/mysqlbackup.sh.erb
=> Allow excludedatabases when using file_per_database

manifests/server/service.pp
Prior to this PR the variable `mysqlsocket` was passed to the `exec` resource in such a way that could allow unsafe executions on the remote host.
This commit fixes the above by properly parameterizing the arguments passed to the `command` and `unless` parameters of the `exec` resource.
The variable is also wrapped with a `shell_escape` for good measure.
=> Harden service class

manifests/server/config.pp
Prior to this commit the variables `dir` and `mysql::server::package_name` were passed to `exec` resources in such a way that could allow unsafe executions on the remote host.
This commit fixes the above by properly parameterizing the arguments passed to each `exec` resource.
Additionally the variables been sanitized with `shell_escape` for good measure.
=> Harden config class

manifests/db.pp, spec/acceptance/01_mysql_db_spec.rb, spec/acceptance/types/mysql_grant_spec.rb, spec/defines/mysql_db_spec.rb
Prior to this commit there was a possibility that malformed strings could be passed in to the resource. 
This could lead to unsafe executions on a remote system.
The parameters that are susceptible are `dbname`, `sql` and `import_cat_cmd`.
In addition, commands were not properly broken out in to arrays of arguments when passed to the exec resource.
This commit fixes the above by adding validation to parameters (where possible) to ensure that the given values conform to expectation.
`dbname` is validated with a regular expression that ensures that it matches expectations set by mysql.
`sql` now only accepts values as an `Array[String]`. 
This can be one or more value. 
Values are also validated with a regular expression that ensures that the given paths are valid.
`import_cat_cmd` has been …
=> Harden db defined type

lib/facter/mysql_version.rb, lib/facter/mysqld_version.rb, spec/unit/facter/mysql_version_spec.rb, spec/unit/facter/mysqld_version_spec.rb
Prior to this PR, this module contained instances of Facter::Util::Resolution.exec and Facter::Util::Resolution.which, which are deprecated. This PR aims to replace these exec helpers with their supported Facter::Core::Execution counterparts.
This PR:
Replaces all Facter::Util::Resolution instances with corresponding Facter::Core::Execution exec helpers
=> (CONT-173) - Updating deprecated facter instances

lib/facter/mysqld_version.rb, manifests/backup/xtrabackup.pp, spec/classes/mysql_backup_xtrabackup_spec.rb, spec/unit/facter/mysqld_version_spec.rb
Since MySQL version 8.0 the backup user needs the following additional privileges:
- SELECT privilege on the _performance_schema.log_status_ table
- SELECT privilege on the _keyring_component_status_ table
- BACKUP_ADMIN privilege on all tables \*.\*
https://docs.percona.com/percona-xtrabackup/latest/using_xtrabackup/privileges.html
=> MySQL 8.0: Grant required privileges to xtrabackup user

spec/classes/mycnf_template_spec.rb, templates/my.cnf.erb
This is needed for newer versions of MariaDB, see issue #1509
=> do not emit other ssl directives when ssl = false

README.md
Prior to this commit the db example shows a String however it is an optional array. 
This commit updates the example from a String to an array.
=> (GH-1516) Update sql example to use array

metadata.json
In codebase hardening efforts the commands are passed as an array, but this feature was only introduced in Puppet 6.24.01. This raises the minimum version to match, since it's no longer possible to use the module on anything older.
=> (GH-1518) Declare minimum Puppet version 6.24.0

REFERENCE.md, lib/puppet/functions/mysql/password.rb
This module configures no potgres, so we should describe the params with mysql instead of postgres.
=> fix naming in documentation

spec/classes/mysql_backup_xtrabackup_spec.rb, templates/xtrabackup.sh.erb
By default `backup_success_file_path` is `undef` what result in a `touch` command without argument that will produce an error like `touch: missing file operand`.
With this merge request we only add the `touch` command to the script when the value of `backup_success_file_path` is defined. 
Also added rspec test for both cases.
=> xtrabackup.sh only touch when backup_success_file_path is set

.github/workflows/nightly.yml, .github/workflows/pr_test.yml, .sync.yml, Gemfile, metadata.json
CONT-494/pin_github_changelog_generator
pdk version: `2.5.0`
=> pdksync - (CONT-494) Pin github_changelog_generator and JSON gem versions

.fixtures.yml
puppetlabs_spec_helper will create the symlink for us, we don't need it in .fixtures.yml.
=> fixtures.yml: Delete legacy symlink

lib/puppet/functions/mysql/password.rb, lib/puppet/functions/mysql_password.rb, spec/functions/mysql_password_spec.rb
Revert broken change of #1557 and fixes the spec test for it by removing the skip.
Fixes #1563
=> Fix broken sensitive parameter for mysql::password

.github/workflows/ci.yml, .github/workflows/nightly.yml
Prior to this commit, deprecation warnings were present in the nightly and ci workflows due to checkout v2 being used rather than v3. This commit updates to v3.
=> (CONT-903) Use checkout@v3

manifests/server.pp
This notify shows as a 'change' in puppet reports, so if you have ssl disabled, every puppet run indicates a resource is changing - which is not the case.  I also feel that it is not this puppet module's place to preach how to configure my systems - even if it is correct.  https://github.com/puppetlabs/puppetlabs-mysql/pull/1512#issuecomment-1326595628 suggests this as well and I agree.
=> remove ssl-disable notify

.github/workflows/ci.yml, .github/workflows/nightly.yml, spec/spec_helper_acceptance_local.rb
Using reusable GitHub actions for this module.
- N/A
- N/A
=> (CONT-1203) - Fixing CI pipeline for Debian & Ubuntu-20

manifests/params.pp, spec/acceptance/05_mysql_xtrabackup_spec.rb, spec/acceptance/types/mysql_plugin_spec.rb, spec/classes/mysql_backup_xtrabackup_spec.rb
With the removal of support for RHEL6 from our modules, work must be done to cleanup and remove any residual code.
This PR does the same for mysql repo module. More info can be found #1498
=> (CAT-1428) Removal of redhat/scientific/oraclelinux 6 for mysql module

.github/workflows/ci.yml, .github/workflows/nightly.yml, README.md
There are supporting binaries of MySQL which are not supported with ARM architecture which are : 
- my_print_defaults
- mysql_config_editor
Skip pipeline for **ARM** based OS, below is list of ARM supported OS : 
- Ubuntu 22.04 
- RHEL-9
=> (CAT-1696) - Skip pipeline for ARM based OS

lib/puppet/functions/mysql/password.rb, spec/acceptance/00_mysql_server_spec.rb, spec/functions/mysql_password_spec.rb
When the password is passed in `<anything-in-caps-with-alpha-numeric>*<alpha-numeric-40-chars-in-caps>` format with Sensitive then the current implementation fails with below error : 
```
Error: Only mysql_native_password (*ABCD...XXX) hashes are supported.
Error: /Stage[main]/Main/Mysql_user[test1@127.0.0.1]/password_hash: change from [old password hash redacted] to [new password hash redacted] failed: Only mysql_native_password (*ABCD...XXX) hashes are supported.
```
This is because the `mysql::password` doesn't handle mentioned condition properly.
=> (CAT-1919) - Handle scenario when user input password in <anything-in-caps-with-alpha-numeric>*<alpha-numeric-40-chars-in-caps>

lib/puppet/functions/mysql/innobackupex_args.rb
Fixing documentation syntax of innobackup function
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> (MAINT) Fixing documentation syntax of innobackup function

manifests/params.pp
The option `expire_logs_days` is deprecated and should no longer be used. This PR removes it from the default configuration.
This change should only have a minor effect on existing installations. Old versions of MySQL (5.7) will fallback to their internal default value of `expire_logs_days`. Newer versions (MySQL 8.0) will probably already use the new option `binlog_expire_logs_seconds`.
This removes the following warning from MySQL's log:
```
[Server] The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead.
```
none
=> Remove deprecated option expire_logs_days from default config

lib/puppet/provider/mysql_user/mysql.rb, spec/unit/puppet/provider/mysql_user/mysql_spec.rb
For the fix, we added a condition where while fetching list of users, we skip users where there is no hostname available.
The acceptance tests were failing for SLES platform. On further inspection, for SLES which was using MariaDB 10.11 version, there was a `PUBLIC` user created by default with no hostname. The filter and mysql expression filters out such cases and fail the resource command.
Mention any related issues or pull requests.
=> Fix spec where mysql_users was failing for SLES

spec/unit/facter/mysql_server_id_spec.rb
Value of the facter :macaddress was nil, causing tests to have two failures (contexts "igalic's laptop" and "node with lo only").
Update the facter initialization allows to pass the tests successfully.
=> Fix spec unit for mysql_server_id

spec/classes/mysql_backup_mysqldump_spec.rb, templates/mysqlbackup.sh.epp
Right now, excluding multiple databases does not work.
This MR aims to fix excluding multiple databases, by revising the respective regular expression.
* When using multiple excluded databases, the list of databases is filtered using `grep -v`. i.e. `grep -v '^\(information_schema|performance_schema\)$`
* When using Basic vs Extended Regular Expressions, the characters `(` and `|` lose their special meaning, the backslashed versions have to be used. For the group (`()`) the escaping has been done, however the alternation is unescaped.
Leading to:
* All the excluded databases will be backed up.
* In case a database is not backuppable (which is why it had been excluded), this leads to the cleanup not being run at all, as it depends on the backup having been successful.
=> Fix backup/rotation with multiple excluded databases

.fixtures.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml, manifests/backup/xtrabackup.pp, manifests/params.pp, manifests/server/installdb.pp, metadata.json, spec/spec_helper_acceptance_local.rb
Add support for Debian 12
- Add all Debian 11 and above platforms to have expected privileges.
- Add ruby package for Debian 12
- When downloading the mariadb-server package '/var/log/mysql' is automatically created for other platforms, but that is not the case with Debian 12. So, make sure the directory is present.
- Debian 12 uses utf8mb3 encoding since utf8 is not supported on it.
- Skip Debian-12-arm platform from tests since the mysql binaries, 'my_print_defaults' and 'mysql_config_editor', are not supported for ARM architecture.
Mention any related issues or pull requests.
=> (CAT-2100) Add Debian 12 support

lib/facter/mysql_version.rb, lib/facter/mysqld_version.rb, lib/puppet/provider/mysql.rb, spec/unit/facter/mysql_version_spec.rb, spec/unit/facter/mysqld_version_spec.rb
Add support for Mariadb 11.x and use its mariadb and mariadbd binaries.
From Mariadb 11.0, mysql* names are deprecated in favor of mariadb* (cf. https://jira.mariadb.org/browse/MDEV-29582).
This pull request is:
- including commits from @OxCom, determining which binaries to use, depending on the mysqld_version facter
- fixing facters for mysql_version and mysqld_version whithin the MariaDB>11 context
- updating/adding tests for this new context
The initial PR #1626 causes [an infinite loop](https://github.com/puppetlabs/puppetlabs-mysql/pull/1626#issuecomment-2236002878) in our case of fresh deployment, because facter is not properly initialized.
This pull request manages to fix #1580 .
=> Add support for Mariadb 11.x
