puppetlabs/puppetlabs-mysql

manifests/server/service.pp

Fixes lint warning introduced by a8fd4d3

Fix lint warning in server/service.pp

---

spec/acceptance/types/mysql_plugin_spec.rb

Fix acceptance tests from #648

---

README.md

Modified Line 49 and 220 to fix broken links

---

CHANGELOG.md
README.md
metadata.json

3.4.0 back to master

---

manifests/server/installdb.pp
manifests/server/service.pp

Fixed server package name so it isn't hardcoded to mysql

---

manifests/backup/mysqlbackup.pp
manifests/backup/mysqldump.pp
manifests/backup/xtrabackup.pp
manifests/server/backup.pp
spec/classes/mysql_server_backup_spec.rb
templates/xtrabackup.sh.erb

This commit implements the 'postscript' functionality for the xtrabackup
provider. It also adds a 'prescript' option to be executed before a
backup.

(MODULES-2340) Implement script functionality for xtrabackup provider

---

manifests/server/backup.pp

Have a look to the following sites:
https://ask.puppetlabs.com/question/13288/whats-the-difference-between-warn-and-warning/
https://docs.puppetlabs.com/puppet/latest/reference/lang_conditional.html?_ga=1.41504802.1433359326.1439356343

Fixes improper use of function 'warn' in backup manifest of server.

---

manifests/server/mysqltuner.pp
metadata.json

Add workarounds to ENTERPRISE-258 and update metadata accordingly.

Compatibility with PE 3.3

---

templates/mysqlbackup.sh.erb

Instead of using password as a command arguments, we are setting MYSQL_ENV variable. See https://dev.mysql.com/doc/refman/5.1/en/password-security-user.html

(MODULES-2605) Use MYSQL_PWD to avoid mysqldump warnings.

---

lib/puppet/parser/functions/mysql_table_exists.rb
spec/unit/puppet/functions/mysql_table_exists_spec.rb

https://github.com/puppetlabs/puppetlabs-mysql/pull/776
rspec test doesn't fail now.

(MODULES-2767) fix mysql_table_exists: add check for args.size, fix rspec test

---

README.md

FM-3333: tuning up mysql readme

---

templates/mysqlbackup.sh.erb

Ensure backup directory or create one if it does not exist!

Ensure backup directory exist

---

lib/puppet/provider/mysql.rb

Fixes:
```
Error: Could not prefetch mysql_user provider 'mysql': Command mysqld is missing
```

make sure we find mysqld on FreeBSD

---

.fixtures.yml
README.md
metadata.json
spec/acceptance/mysql_backup_spec.rb
spec/spec_helper_acceptance.rb

Also updates staging module dependency.

Skips mysqlbackup.sh tests on MySQL 5.7+

---

spec/acceptance/types/mysql_grant_spec.rb

On MySQL 5.7+ the procedure needs to be created first before a grant can be applied towards it.

Fixes procedure grant tests for 5.7.12

---

README.md

Some edits on the mariaDB install instructions.

edits on mariadb install example

---

.sync.yml
Gemfile

https://github.com/puppetlabs/modulesync_configs/pull/102

(MODULES-3631) msync Gemfile for 1.9 frozen strings

---

spec/unit/puppet/type/mysql_grant_spec.rb

I made a CI fix in PR #935 and spec tests passed on both my machine and on travis because mysql is running on both and as such the mysql_version fact returned a correct value and the test passed. However when running in jenkins, mysql is not installed on the SUT's that the spec tests run on and as such we need to stub the mysql_version fact value.

(maint) Fix PROXY privilege spec test when mysql not installed on SUT

---

templates/mysqlbackup.sh.erb

Solaris' find does not support -maxdepth. One need to use gfind to make this work.
Kind Regards
Oliver

Use gfind on solaris

---

locales/puppetlabs-mysql.pot

This is adding a POT file for the module.

(FM-6116) - Adding POT file for metadata.json

---

CHANGELOG.md

Sections have been broken by
https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

[maint] Fix CHANGELOG markdown sections

---

spec/acceptance/types/mysql_grant_spec.rb

Adding SLES to a condition that runs an extra step as part of a test.
This allows the tests to pass.

(MODULES-4761) Fixing SLES12 acceptance tests

---

README.md

little fixes before Japanese translation finalized

fixing typos pre-jp translation

---

README.md

Just a fix in the table of contents.

(MODULES-4698) fix before translation release

---

manifests/db.pp

remove provider parameter from $user_resource in mysql::db

(MODULES-4115) Invalid parameter provider on Mysql_user[user@localhost] in mysql::db

---

.travis.yml
CONTRIBUTING.md
locales/config.yaml

Once this is merged, it’d be much appreciated if the merger could remove the `msync_18sep17_892c4cf` branch from the `puppetlabs` fork. 
Thank you! 💖

(maint) modulesync 892c4cf

---

spec/acceptance/locales_spec.rb

Updating test to run on multiple versions of mysql.

Updating test to support multiple versions of error messages

---

README.md

This comment isn't especially helpful and confused translation

cut out an unnecessary comment in code sample

---

locales/ja/puppetlabs-mysql.po

Currently some of the strings are not fully matching, this results in
translations not being displayed.

Updating PO file to match strings in POT file and code base.

---

CHANGELOG.md

Updating CHANGELOG so that version number is a link.

Updating link

---

spec/spec_helper_acceptance.rb

Updating to reflect change in Bolt:
https://github.com/puppetlabs/bolt/pull/129/files

Update modules to modulepath

---

metadata.json

Dependency bump as puppet/staging 3.0.0 has been released.

(MODULES-6175) - Updating puppet/staging dependency

---

tasks/export.json

changed option in export.json from sql to file, probably a copy paste error

changed input param option in export.json from sql to file

---

manifests/backup/xtrabackup.pp

PROCESS is now required

---

README.md
readmes/README_ja_JP.md

I fixed it because there was a typo in the README file 🙏

Type fix in "REAME.md".

---

manifests/params.pp
spec/acceptance/mysql_server_spec.rb
spec/classes/mysql_bindings_spec.rb
spec/classes/mysql_client_spec.rb

I added the variables daemon_dev_package_name, client_dev_package_name and includedir for Archlinux in the params.pp file. I also disabled Archlinux for tests on two classes, they don't support archlinux.

fix archlinux compatibility

---

CHANGELOG.md

This commit edited the changelog to make it consistent re. tense and capitalization.

(MODULES-7161) Minor changelog edits

---

README.md
examples/mysql_plugin.pp

Hi, 
we ran into some issues when using the mysql_plugin Type and the documentation wasn't up2date. So we fixed it. 
Cheers,
Markus

Fix mysql_plugin examples and add section in README

---

CHANGELOG.md
metadata.json

PR to merge the release branch (8.0.0 version) back into the master

(MODULES-8503) - 8.0.0 Merge Back

---

manifests/backup/xtrabackup.pp

We have our own backup script with some additional features, of which
quite a few are specific for our platform. I could add some of them
here as well, but this would end up in a completely new script.
That's why I try it with this minimally invasive variant :)

Allow own Xtrabackup script

---

CHANGELOG.md
metadata.json

(MODULES-9242) - Release Merge back 9.1.0

---

lib/puppet/provider/mysql.rb
lib/puppet/provider/mysql_datadir/mysql.rb

See: https://tickets.puppetlabs.com/browse/MODULES-9061

add support for rh-mariadb102

---

CHANGELOG.md
REFERENCE.md
manifests/server/backup.pp
metadata.json

(MODULES-9636) - Release Merge back v10.1.0

---

metadata.json
provision.yaml

(FM-8677) - Support added for CentOS 8

---

README.md

Hi - thanks for this great forge module. It got me over the line when I was forced to use mariadb
Just reviewing my code, and the service name on xenial is mysqld, not mysql, so I thought I'd take the opportunity to refresh this part of the doc, as I copy/pasted verbatim!

Update README.md Ubuntu example to xenial

---

.github/workflows/release.yml
.github/workflows/weekly.yml
.sync.yml
.travis.yml
manifests/params.pp
metadata.json
provision.yaml
spec/acceptance/types/mysql_grant_spec.rb

(IAC-746) - Add ubuntu 20.04 support

---

CHANGELOG.md
metadata.json

Tested Mergeback PR for the Test Results

(maint) Release MergeBack v10.9.0

---

spec/functions/mysql_password_spec.rb

This is required due to: https://tickets.puppetlabs.com/browse/IAC-1677

(maint) Comment out pending test

---

manifests/params.pp
metadata.json

(IAC-1753) - Add Support for AlmaLinux 8
pdk version: `2.2.0`

pdksync - (IAC-1753) - Add Support for AlmaLinux 8

---

CHANGELOG.md
metadata.json

Please verify before merging:
☐ last [nightly](https://github.com/puppetlabs/puppetlabs-mysql/actions/workflows/nightly.yml) run is green
☐ [Changelog](https://github.com/puppetlabs/puppetlabs-mysql/blob/main/CHANGELOG.md) is readable and has no unlabeled pull requests
☐ Ensure the [changelog](https://github.com/puppetlabs/puppetlabs-mysql/blob/main/CHANGELOG.md) version and [metadata](https://github.com/puppetlabs/puppetlabs-mysql/blob/main/metadata.json) version match

(Maint) Release prep v12.0.3

---

CHANGELOG.md
metadata.json

Remember to check for:
- Green nightlies
- Readable CHANGELOG
- Correct new version in metadata.json

(Release) V13.2.0 Release prep

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

(MAINT) - Add env variables to ci
pdk version: `2.7.1` 
Removed duplicate step `Run validation steps` as validation already carried out in module_ci.yml

pdksync - (MAINT) - Add env variables to ci

---

manifests/backup/mysqlbackup.pp
manifests/backup/mysqldump.pp
manifests/backup/xtrabackup.pp
manifests/server/config.pp
manifests/server/service.pp
metadata.json
spec/acceptance/05_mysql_xtrabackup_spec.rb

(MAINT) - Update Stdlib dependency
pdk version: `2.7.1`

pdksync - (MAINT) - Allow Stdlib 9.x

---

spec/default_facts.yml
spec/spec_helper.rb

(maint) - Replace legacy facts in spec/default_facts.yml
pdk version: `2.7.1`

pdksync - (maint) - Replace legacy facts in spec/default_facts.yml

---

.sync.yml
Gemfile
Rakefile
metadata.json

(MAINT) PDK Update
pdk version: `3.0.0`

pdksync - (MAINT) PDK Update

---

.github/workflows/release.yml
.gitignore
.pdkignore
.rubocop.yml
.vscode/extensions.json
Gemfile
metadata.json
spec/classes/mysql_server_spec.rb
spec/spec_helper.rb

(PF-3525) - pdk update for module
pdk version: `3.2.0`

pdksync - (PF-3525) - pdk update for module
